import js from '@eslint/js'
import ts from 'typescript-eslint'
import svelte from 'eslint-plugin-svelte'
import svelteParser from 'svelte-eslint-parser'
import globals from 'globals'

export default [
  {
    ignores: [
      'out/**',
      'dist-packages/**',
      'node_modules/**',
      'legacy/**',
      // Generated by `cap add android` and regenerated by `cap sync`. Linting
      // it reports thousands of problems in code nobody here writes, and any
      // fix would be overwritten by the next sync.
      'mobile/android/**',
    ],
  },
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  {
    // Renderer code runs in a browser context; main and preload do not.
    files: ['src/renderer/**/*.{ts,svelte}'],
    languageOptions: { globals: globals.browser },
  },
  {
    files: ['src/main/**/*.ts', 'src/preload/**/*.ts'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
  {
    /*
      Electron keeps one listener per webRequest event per session, so a
      second `onSendHeaders` (or `onCompleted`, `onErrorOccurred`) on the same
      session silently replaces the first. Casting did exactly that to the
      player's count of unanswered requests. Observers go through
      `src/main/webrequesthub.ts`, which shares one listener among them.
    */
    files: ['src/main/**/*.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "CallExpression[callee.object.property.name='webRequest'][callee.property.name=/^on(SendHeaders|Completed|ErrorOccurred)$/]",
          message:
            'Observe requests through webrequesthub.ts: a second listener on the same session silently replaces the first. See eslint.config.js.',
        },
      ],
    },
  },
  {
    // The phone bridge is browser code that imports the business layer.
    files: ['mobile/src/**/*.ts'],
    languageOptions: { globals: globals.browser },
  },
  {
    /*
      Build and diagnostic scripts run under Node, and `preview-mobile.cjs` is
      CommonJS on purpose — it is loaded by the Electron binary as a main
      script, which resolves `.cjs` without the package needing a type field.
    */
    files: ['scripts/**/*.{js,cjs,mjs,ts}', '*.config.ts', 'mobile/vite.config.ts'],
    languageOptions: { globals: { ...globals.node } },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    // `.svelte.ts` modules use runes, so they need the Svelte parser too — the
    // plain TS parser chokes on `$state<T>(...)` at the top level.
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: { parser: svelteParser, parserOptions: { parser: ts.parser } },
  },
  {
    rules: {
      // The original swallowed 36 errors in empty catch blocks. An unused
      // binding is fine when prefixed, but a silent catch is not.
      'no-empty': ['error', { allowEmptyCatch: false }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    /*
      An event callback handed to the preload must not *return* anything.

      On the desktop, `window.wta` and `window.wtaChrome` cross Electron's
      context bridge, which clones a callback's return value back across it.
      `(next) => (state = next)` returns the assigned value, and Svelte 5 has
      wrapped an object in a reactive proxy by then — which cannot be cloned.
      The assignment still happens, then "An object could not be cloned" is
      thrown in the preload and every later listener on that channel is
      skipped. Found 2026-09-27 on eight subscriptions, the source-switch
      offer among them. A statement body returns nothing and cannot hit it.
    */
    files: ['src/renderer/**/*.{ts,svelte}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "CallExpression[callee.object.property.name='on'] > ArrowFunctionExpression[body.type='AssignmentExpression'], CallExpression[callee.property.name=/^on[A-Z]/] > ArrowFunctionExpression[body.type='AssignmentExpression']",
          message:
            'Give this event callback a statement body: its return value crosses the context bridge, and a returned Svelte proxy cannot be cloned. See eslint.config.js.',
        },
      ],
    },
  },
]
