import { builtinModules } from 'node:module'
import js from '@eslint/js'
import ts from 'typescript-eslint'
import svelte from 'eslint-plugin-svelte'
import svelteParser from 'svelte-eslint-parser'
import globals from 'globals'
import { phoneReach } from './tools/phonereach.js'

/*
  Code that runs without Node or Electron: everything in src/shared, which the
  renderer imports too, and every file the phone's bundle reaches. The second
  set is not kept by hand. It is worked out from the imports on every run
  (tools/phonereach.js), so a module the bridge starts importing is covered
  from that moment, with everything it imports in turn.
*/
const PORTABLE = ['src/shared/**/*.ts', ...phoneReach(import.meta.dirname).files]

const PORTABLE_IMPORT =
  'This module runs where there is no Node and no Electron: the phone reaches it (tools/phonereach.js), or it is in src/shared. Keep the platform part behind a port, as scanservice.ts and bridge/scan.ts do. A type-only import is fine.'

/** Node's built-in modules by every name they answer to, and Electron's. */
const NOT_PORTABLE = [...builtinModules, 'electron'].map((name) => ({
  name,
  message: PORTABLE_IMPORT,
  allowTypeImports: true,
}))

/** Node's globals, which a WebView does not have. */
const NODE_GLOBALS = [
  {
    name: 'process',
    message:
      'A WebView has no `process`; read it as `globalThis.process?.…`, which says it may be missing (see identity.ts). 2.0.11 blanked the phone at startup on an unguarded read.',
  },
  {
    name: 'Buffer',
    message: 'A WebView has no `Buffer`: use Uint8Array, TextEncoder and TextDecoder.',
  },
  { name: '__dirname', message: 'Node only: this module runs where there is no file system path.' },
  {
    name: '__filename',
    message: 'Node only: this module runs where there is no file system path.',
  },
  { name: 'require', message: 'Node only: use an import.' },
  { name: 'global', message: 'Node only: use `globalThis`.' },
  { name: 'setImmediate', message: 'Node only: use `setTimeout` or `queueMicrotask`.' },
]

export default [
  {
    ignores: [
      'out/**',
      'dist-packages/**',
      'node_modules/**',
      'legacy/**',
      // Generated by `cap add android` and regenerated by `cap sync`. Linting
      // it reports thousands of problems in code nobody here writes, and any
      // fix would be overwritten by the next sync.
      'mobile/android/**',
    ],
  },
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  {
    // Renderer code runs in a browser context; main and preload do not.
    files: ['src/renderer/**/*.{ts,svelte}'],
    languageOptions: { globals: globals.browser },
  },
  {
    files: ['src/main/**/*.ts', 'src/preload/**/*.ts'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
  {
    /*
      Electron keeps one listener per webRequest event per session, so a
      second `onSendHeaders` (or `onCompleted`, `onErrorOccurred`) on the same
      session silently replaces the first. Casting did exactly that to the
      player's count of unanswered requests. Observers go through
      `src/main/webrequesthub.ts`, which shares one listener among them.
    */
    files: ['src/main/**/*.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "CallExpression[callee.object.property.name='webRequest'][callee.property.name=/^on(SendHeaders|Completed|ErrorOccurred)$/]",
          message:
            'Observe requests through webrequesthub.ts: a second listener on the same session silently replaces the first. See eslint.config.js.',
        },
      ],
    },
  },
  {
    // The phone bridge is browser code that imports the business layer.
    files: ['mobile/src/**/*.ts'],
    languageOptions: { globals: globals.browser },
  },
  {
    /*
      The portable layer: no Node, no Electron, no Node globals. "src/main is
      the business layer, not the Electron half" was a rule nothing checked
      until 2026-10, by when 28 files there touched Node or Electron and the
      docs still said six. See PORTABLE above for which files this covers.
      Tests and fixtures run under Node on purpose.
    */
    files: PORTABLE,
    ignores: ['**/*.test.ts', '**/*.fixture.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          paths: NOT_PORTABLE,
          patterns: [
            { group: ['node:*', 'electron/*'], message: PORTABLE_IMPORT, allowTypeImports: true },
          ],
        },
      ],
      'no-restricted-globals': ['error', ...NODE_GLOBALS],
    },
  },
  {
    /*
      Build and diagnostic scripts run under Node, and `preview-mobile.cjs` is
      CommonJS on purpose — it is loaded by the Electron binary as a main
      script, which resolves `.cjs` without the package needing a type field.
    */
    files: [
      'scripts/**/*.{js,cjs,mjs,ts}',
      'tools/**/*.js',
      '*.config.ts',
      'mobile/vite.config.ts',
    ],
    languageOptions: { globals: { ...globals.node } },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    // `.svelte.ts` modules use runes, so they need the Svelte parser too — the
    // plain TS parser chokes on `$state<T>(...)` at the top level.
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: { parser: svelteParser, parserOptions: { parser: ts.parser } },
  },
  {
    rules: {
      // The original swallowed 36 errors in empty catch blocks. An unused
      // binding is fine when prefixed, but a silent catch is not.
      'no-empty': ['error', { allowEmptyCatch: false }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    /*
      An event callback handed to the preload must not *return* anything.

      On the desktop, `window.wta` and `window.wtaChrome` cross Electron's
      context bridge, which clones a callback's return value back across it.
      `(next) => (state = next)` returns the assigned value, and Svelte 5 has
      wrapped an object in a reactive proxy by then — which cannot be cloned.
      The assignment still happens, then "An object could not be cloned" is
      thrown in the preload and every later listener on that channel is
      skipped. Found 2026-09-27 on eight subscriptions, the source-switch
      offer among them. A statement body returns nothing and cannot hit it.
    */
    files: ['src/renderer/**/*.{ts,svelte}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "CallExpression[callee.object.property.name='on'] > ArrowFunctionExpression[body.type='AssignmentExpression'], CallExpression[callee.property.name=/^on[A-Z]/] > ArrowFunctionExpression[body.type='AssignmentExpression']",
          message:
            'Give this event callback a statement body: its return value crosses the context bridge, and a returned Svelte proxy cannot be cloned. See eslint.config.js.',
        },
      ],
    },
  },
]
