import js from '@eslint/js'
import ts from 'typescript-eslint'
import svelte from 'eslint-plugin-svelte'
import svelteParser from 'svelte-eslint-parser'
import globals from 'globals'

export default [
  {
    ignores: [
      'out/**',
      'dist-packages/**',
      'node_modules/**',
      'legacy/**',
      // Generated by `cap add android` and regenerated by `cap sync`. Linting
      // it reports thousands of problems in code nobody here writes, and any
      // fix would be overwritten by the next sync.
      'mobile/android/**',
    ],
  },
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  {
    // Renderer code runs in a browser context; main and preload do not.
    files: ['src/renderer/**/*.{ts,svelte}'],
    languageOptions: { globals: globals.browser },
  },
  {
    files: ['src/main/**/*.ts', 'src/preload/**/*.ts'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
  {
    // The phone bridge is browser code that imports the business layer.
    files: ['mobile/src/**/*.ts'],
    languageOptions: { globals: globals.browser },
  },
  {
    /*
      Build and diagnostic scripts run under Node, and `preview-mobile.cjs` is
      CommonJS on purpose — it is loaded by the Electron binary as a main
      script, which resolves `.cjs` without the package needing a type field.
    */
    files: ['scripts/**/*.{js,cjs,mjs,ts}', '*.config.ts', 'mobile/vite.config.ts'],
    languageOptions: { globals: { ...globals.node } },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    // `.svelte.ts` modules use runes, so they need the Svelte parser too — the
    // plain TS parser chokes on `$state<T>(...)` at the top level.
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: { parser: svelteParser, parserOptions: { parser: ts.parser } },
  },
  {
    rules: {
      // The original swallowed 36 errors in empty catch blocks. An unused
      // binding is fine when prefixed, but a silent catch is not.
      'no-empty': ['error', { allowEmptyCatch: false }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
]
