/**
 * Which sources can put a title on the television.
 *
 * ## The receiver's rule
 *
 * A plain Chromecast running the Default Media Receiver plays one whole MP4 or
 * WebM file and refuses HLS outright, before it fetches anything — measured
 * 2026-09-13 against the owner's dongle with a textbook stream generated by
 * ffmpeg, so it is the device and not this app. The owner chose on 2026-09-13,
 * and again on 2026-09-26, not to build the custom receiver that would lift it.
 * So a source can cast a title exactly when it hands out a whole file for it.
 *
 * ## Two levels of evidence
 *
 * **Per title**, from tests and casts, decisive where it exists: how the video
 * arrived (`StreamDelivery`), and, stronger, what a television said when it
 * was cast (`CastOutcome`).
 *
 * **Per source**, from every title, for the titles nothing has tested. The
 * owner's first expectation was that this is the whole story — that a
 * source's format is fixed, so testing each once would do. For most it is:
 * the netocdn family and Videasy served playlists on every title measured.
 * But not for all. VidSrc handed out a whole file on 2026-09-13 and a
 * playlist on 2026-09-26; VidLux gave a 297 MB MP4 for Silo while resolving
 * other titles to a host that serves playlists. So the per-source answer only
 * fills gaps, and says "likely", never "yes".
 */

import { RESULT_TTL_MS, testedAtOf } from './scanrow'
import type { ProviderScan, StreamDelivery } from './types'

/**
 * The content types a whole file is handed to the receiver as.
 *
 * The cast path uses this same test to decide what to send (`castservice.ts`,
 * `bridge/cast.ts`), and a test uses it to record `progressive` — so "this
 * source casts" and "the cast sends it" cannot disagree. A whole file of any
 * other type, ScreenScape's MKV among them, is `other`: whether the dongle
 * would play MKV is not measured, so it is not sent.
 */
const CASTABLE_FILE_TYPES = ['video/mp4', 'video/webm']

/** Whether a whole file with this `Content-Type` is one the receiver is given. */
export function isCastableFileType(contentType: string): boolean {
  const type = contentType.trim().toLowerCase()
  return CASTABLE_FILE_TYPES.some((known) => type.startsWith(known))
}

/** How a whole file counts, by its `Content-Type`. */
export function wholeFileDelivery(contentType: string): 'progressive' | 'other' {
  return isCastableFileType(contentType) ? 'progressive' : 'other'
}

/**
 * Which delivery describes a page that showed more than one.
 *
 * The one a cast would send: `identifyStream` takes a whole castable file over
 * a playlist wherever it finds both, so a test that saw both must record the
 * file, or it would call a source uncastable that casts. After that, a
 * playlist over another container (the cast would try the playlist), and
 * `unknown` — a video playing with nothing seen feeding it — only when there
 * is nothing else.
 */
export function strongerDelivery(held: StreamDelivery | null, seen: StreamDelivery): StreamDelivery {
  const rank: Record<StreamDelivery, number> = { progressive: 0, segmented: 1, other: 2, unknown: 3 }
  return held !== null && rank[held] <= rank[seen] ? held : seen
}

/**
 * What the cast list may say about one source for one title.
 *
 * - `yes` — this title: a whole file was seen, or a cast of it played.
 * - `likely` — nothing about this title, but the source has handed out a whole
 *   file for another one.
 * - `unknown` — nothing either way.
 * - `no` — this title: only playlists, another container, or the television
 *   refused it. Or, with nothing about this title, a source that has never
 *   been seen handing out anything but playlists.
 */
export type Castability = 'yes' | 'likely' | 'unknown' | 'no'

/** What is known about casting this title from this source, or null for nothing. */
export function titleCastability(scan: ProviderScan | null | undefined, providerId: string): 'yes' | 'no' | null {
  // The television's own answer outranks any prediction of it.
  const cast = scan?.casts?.[providerId]
  if (cast) return cast === 'played' ? 'yes' : 'no'
  switch (scan?.delivery?.[providerId]) {
    case 'progressive':
      return 'yes'
    case 'segmented':
    case 'other':
      return 'no'
    default:
      // `unknown`, or tested before deliveries were recorded.
      return null
  }
}

/**
 * What a source has done across every title, for a title nothing has tested.
 *
 * One whole file anywhere makes it `likely`: the cost of a wrong "likely" is
 * one failed try, after which that title knows better. Only a source seen
 * handing out playlists and never a file is `no`. Results past their lifetime
 * do not count, which is what lets a source that changed format stop being
 * judged by its old one.
 */
export function sourceCastability(
  rows: readonly ProviderScan[],
  providerId: string,
  now: number,
): 'likely' | 'no' | null {
  let refused = false
  for (const row of rows) {
    // A cast is stored with a verdict and a time like any test, so this
    // covers both kinds of evidence.
    const testedAt = testedAtOf(row, providerId)
    if (testedAt === null || now - testedAt > RESULT_TTL_MS) continue
    const answer = titleCastability(row, providerId)
    if (answer === 'yes') return 'likely'
    if (answer === 'no') refused = true
  }
  return refused ? 'no' : null
}

/**
 * Castability for each source, for one title: the title's own evidence where
 * there is any, the source's record everywhere else.
 *
 * `titleScan` is the title's row as this device reads it — its own results
 * with the other devices' good news filled in (`scanshare.ts`). `rows` is every
 * row there is, own and shared, for the per-source record.
 */
export function castabilities(
  providerIds: readonly string[],
  titleScan: ProviderScan | null,
  rows: readonly ProviderScan[],
  now: number,
): Record<string, Castability> {
  const out: Record<string, Castability> = {}
  for (const id of providerIds) {
    const forTitle = titleCastability(titleScan, id)
    out[id] = forTitle ?? sourceCastability(rows, id, now) ?? 'unknown'
  }
  return out
}
