/**
 * Real stream headers, for `streamsignature.test.ts` and the parsers' own
 * tests: what a television would have to decode, as ffmpeg writes it.
 *
 * Made by ffmpeg (libx264, libx265, aac, ac3, eac3, libmp3lame) rather than
 * by hand, for the reason `initsegment.fixture.ts` gives. Init segments are
 * what `-f hls -hls_segment_type fmp4` writes as `#EXT-X-MAP`; TS openings are
 * the start of a `-f mpegts` file cut two packets after the one holding the
 * SPS, as in `transportstream.fixture.ts`; the whole file is the head of an
 * MP4 written with `-movflags +faststart`, its `moov` before its `mdat`.
 * x265 runs with `info=0`, which leaves its settings out of the headers and
 * the fixtures small. For example:
 *
 *     ffmpeg -f lavfi -i testsrc=size=2160x1080:rate=24 -f lavfi -i sine -t 1 \
 *       -pix_fmt yuv420p -c:v libx264 -profile:v high -c:a aac -f mpegts out.ts
 */

const bytes = (base64: string): Uint8Array => new Uint8Array(Buffer.from(base64, 'base64'))

/** fMP4 init: HEVC Main 10 (`-pix_fmt yuv420p10le`), 3840x1600 at 24 fps, with E-AC-3 audio. */
export const INIT_HEVC_MAIN10_3840X1600_EAC3 = bytes(
  'AAAAIGZ0eXBpc281AAACAGlzbzVpc282ZGJ5MW1wNDEAAAVRbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAFYiAAAAAAAAQAAAQAA' +
  'AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAA' +
  'Am50cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA' +
  'AAAAAAAAAAAAAABAAAAADwAAAAZAAAAAAAAwZWR0cwAAAChlbHN0AAAAAAAAAAIAABy2/////wABAAAAAAAAAAAEAAABAAAAAAHa' +
  'bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAwAAAAAABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hh' +
  'bmRsZXIAAAABhW1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAUVz' +
  'dGJsAAAA+XN0c2QAAAAAAAAAAQAAAOlodmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAADwAGQABIAAAASAAAAAAAAAABFExhdmM2' +
  'My4xLjEwMiBsaWJ4MjY1AAAAAAAAAAAAAAAAGP//AAAAeWh2Y0MBAiAAAACQAAAAAACW8AD8/fr6AAAPA6AAAQAYQAEMAf//AiAA' +
  'AAMAkAAAAwAAAwCWlZgJoQABACxCAQECIAAAAwCQAAADAAADAJagAeAgBkE2WVmkkyvAWgIAAAMAAgAAAwAwEKIAAQAHRAHBcrRi' +
  'QAAAAApmaWVsAQAAAAAQcGFzcAAAAAEAAAABAAAAEHN0dHMAAAAAAAAAAAAAABBzdHNjAAAAAAAAAAAAAAAUc3RzegAAAAAAAAAA' +
  'AAAAAAAAABBzdGNvAAAAAAAAAAAAAAHGdHJhawAAAFx0a2hkAAAAAwAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAABAQAA' +
  'AAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAMGVkdHMAAAAoZWxzdAAAAAAAAAACAAAatv//' +
  '//8AAQAAAAAAAAAAAAAAAQAAAAABMm1kaWEAAAAgbWRoZAAAAAAAAAAAAAAAAAAArEQAAAAAVcQAAAAAAC1oZGxyAAAAAAAAAABz' +
  'b3VuAAAAAAAAAAAAAAAAU291bmRIYW5kbGVyAAAAAN1taW5mAAAAEHNtaGQAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAA' +
  'AQAAAAx1cmwgAAAAAQAAAKFzdGJsAAAAVXN0c2QAAAAAAAAAAQAAAEVlYy0zAAAAAAAAAAEAAAAAAAAAAAABABAAAAAArEQAAAAA' +
  'AA1kZWMzAwBgAgAAAAAUYnRydAAAAAAAAXcAAAF3AAAAABBzdHRzAAAAAAAAAAAAAAAQc3RzYwAAAAAAAAAAAAAAFHN0c3oAAAAA' +
  'AAAAAAAAAAAAAAAQc3RjbwAAAAAAAAAAAAAASG12ZXgAAAAgdHJleAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAACB0cmV4AAAA' +
  'AAAAAAIAAAABAAAAAAAAAAAAAAAAAAAAYXVkdGEAAABZbWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAA' +
  'AAAsaWxzdAAAACSpdG9vAAAAHGRhdGEAAAABAAAAAExhdmY2My4xLjEwMg==',
)

/** fMP4 init: H.264 High, 1920x1080 at 25 fps, with AC-3 audio. */
export const INIT_H264_HIGH_1080_AC3 = bytes(
  'AAAAIGZ0eXBpc281AAACAGlzbzVpc282ZGJ5MW1wNDEAAAUEbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAACsRAAAAAAAAQAAAQAA' +
  'AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAA' +
  'AiN0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA' +
  'AAAAAAAAAAAAAABAAAAAB4AAAAQ4AAAAAAAwZWR0cwAAAChlbHN0AAAAAAAAAAIAAA3I/////wABAAAAAAAAAAAEAAABAAAAAAGP' +
  'bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAyAAAAAABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hh' +
  'bmRsZXIAAAABOm1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAPpz' +
  'dGJsAAAArnN0c2QAAAAAAAAAAQAAAJ5hdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAB4AEOABIAAAASAAAAAAAAAABFExhdmM2' +
  'My4xLjEwMiBsaWJ4MjY0AAAAAAAAAAAAAAAAGP//AAAAOGF2Y0MBZAAo/+EAG2dkACis2UB4AiflwEQAAAMABAAAAwDIPGDGWAEA' +
  'Bmjr48siwP34+AAAAAAQcGFzcAAAAAEAAAABAAAAEHN0dHMAAAAAAAAAAAAAABBzdHNjAAAAAAAAAAAAAAAUc3RzegAAAAAAAAAA' +
  'AAAAAAAAABBzdGNvAAAAAAAAAAAAAAHEdHJhawAAAFx0a2hkAAAAAwAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAABAQAA' +
  'AAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAMGVkdHMAAAAoZWxzdAAAAAAAAAACAAAMyP//' +
  '//8AAQAAAAAAAAAAAAAAAQAAAAABMG1kaWEAAAAgbWRoZAAAAAAAAAAAAAAAAAAArEQAAAAAVcQAAAAAAC1oZGxyAAAAAAAAAABz' +
  'b3VuAAAAAAAAAAAAAAAAU291bmRIYW5kbGVyAAAAANttaW5mAAAAEHNtaGQAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAA' +
  'AQAAAAx1cmwgAAAAAQAAAJ9zdGJsAAAAU3N0c2QAAAAAAAAAAQAAAENhYy0zAAAAAAAAAAEAAAAAAAAAAAABABAAAAAArEQAAAAA' +
  'AAtkYWMzUAjAAAAAFGJ0cnQAAAAAAAF3AAABdwAAAAAQc3R0cwAAAAAAAAAAAAAAEHN0c2MAAAAAAAAAAAAAABRzdHN6AAAAAAAA' +
  'AAAAAAAAAAAAEHN0Y28AAAAAAAAAAAAAAEhtdmV4AAAAIHRyZXgAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAgdHJleAAAAAAA' +
  'AAACAAAAAQAAAAAAAAAAAAAAAAAAAGF1ZHRhAAAAWW1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAA' +
  'LGlsc3QAAAAkqXRvbwAAABxkYXRhAAAAAQAAAABMYXZmNjMuMS4xMDI=',
)

/** TS: H.264 High level 5.0, 2160x1080 at 24 fps, with AAC: the shape of Videasy's stream the owner's Chromecast refused (2026-09-26). */
export const TS_H264_HIGH_2160X1080 = bytes(
  'R0AREABC8CUAAcEAAP8B/wAB/IAUSBIBBkZGbXBlZwlTZXJ2aWNlMDF3fEPK////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////////////////////////////////////////////////9HQAAQAACwDQABwQAAAAHwACqxBLL/////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '/0dQABAAArAXAAHBAADhAPAAG+EA8AAP4QHwAC9EuZv/////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////R0EAMAdQAAB7DH4AAAAB4AAAgMAKMQAJEvkRAAfYYQAAAAEJ' +
  '8AAAAAFnZAAyrNlAIcCJ+XARAAADAAEAAAMAMA8YMZYAAAABaOvjyyLAAAABBgX//6vcRem95tlIt5Ys2CDZI+7veDI2NCAtIGNv' +
  'cmUgMTY1IHIzMjIyIGIzNTYwNWEgLSBILjI2NC9NUEVHLTQgQVZDIGNvZGVjIC0gQ29weWxlZnQgMjAwMy0yMDI1IC0gaHR0cDov' +
  'L3dHAQARd3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFs' +
  'eXNlPTB4MzoweDExMyBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2' +
  'IGNocm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MSBjcW09MCBkZUcBABJhZHpvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9t' +
  'YV9xcF9vZmZzZXQ9LTIgdGhyZWFkcz0yNCBsb29rYWhlYWRfdGhyZWFkcz00IHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0' +
  'ZT0xIGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTMgYl9weXJhbWlkPTIg' +
  'Yl9h',
)

/** TS: H.264 Main, 1280x720 at 30 fps, with AC-3 as ATSC lists it (stream type 0x81). */
export const TS_H264_MAIN_720_AC3 = bytes(
  'R0AREABC8CUAAcEAAP8B/wAB/IAUSBIBBkZGbXBlZwlTZXJ2aWNlMDF3fEPK////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////////////////////////////////////////////////9HQAAQAACwDQABwQAAAAHwACqxBLL/////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '/0dQABAAArAdAAHBAADhAPAAG+EA8ACB4QHwBgUEQUMtM85Q/Lz/////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////R0EAMAdQAAB7DH4AAAAB4AAAgMAKMQAJB0ERAAfYYQAAAAEJ' +
  '8AAAAAFnTUAf7KAoAt2AiAAAAwAIAAADAeB4wYywAAAAAWjr48sgAAABBgX//6vcRem95tlIt5Ys2CDZI+7veDI2NCAtIGNvcmUg' +
  'MTY1IHIzMjIyIGIzNTYwNWEgLSBILjI2NC9NUEVHLTQgQVZDIGNvZGVjIC0gQ29weWxlZnQgMjAwMy0yMDI1IC0gaHR0cDovL3d3' +
  'dy5HAQARdmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFseXNl' +
  'PTB4MToweDExMSBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2IGNo' +
  'cm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MCBjcW09MCBkZWFkekcBABJvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9tYV9x' +
  'cF9vZmZzZXQ9LTIgdGhyZWFkcz0yMiBsb29rYWhlYWRfdGhyZWFkcz0zIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0x' +
  'IGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTMgYl9weXJhbWlkPTIgYl9h' +
  'ZGFw',
)

/** TS: H.264 Main, 1280x720, with E-AC-3 as DVB lists it (`-mpegts_flags system_b`: private data, stream type 0x06, and an E-AC-3 descriptor). */
export const TS_H264_MAIN_720_EAC3_DVB = bytes(
  'R0AREABC8CUAAcEAAP8B/wAB/IAUSBIBBkZGbXBlZwlTZXJ2aWNlMDF3fEPK////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////////////////////////////////////////////////9HQAAQAACwDQABwQAAAAHwACqxBLL/////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '/0dQABAAArAgAAHBAADhAPAAG+EA8AAG4QHwCQUERUFDM3oBAFoXv+z/////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////R0EAMAdQAAB7DH4AAAAB4AAAgMAKMQAJB0ERAAfYYQAAAAEJ' +
  '8AAAAAFnTUAf7KAoAt2AiAAAAwAIAAADAeB4wYywAAAAAWjr48sgAAABBgX//6vcRem95tlIt5Ys2CDZI+7veDI2NCAtIGNvcmUg' +
  'MTY1IHIzMjIyIGIzNTYwNWEgLSBILjI2NC9NUEVHLTQgQVZDIGNvZGVjIC0gQ29weWxlZnQgMjAwMy0yMDI1IC0gaHR0cDovL3d3' +
  'dy5HAQARdmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFseXNl' +
  'PTB4MToweDExMSBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2IGNo' +
  'cm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MCBjcW09MCBkZWFkekcBABJvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9tYV9x' +
  'cF9vZmZzZXQ9LTIgdGhyZWFkcz0yMiBsb29rYWhlYWRfdGhyZWFkcz0zIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0x' +
  'IGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTMgYl9weXJhbWlkPTIgYl9h' +
  'ZGFw',
)

/** TS: H.264 High level 4.2, 1920x1080 at 60 fps, with MP3 audio. */
export const TS_H264_HIGH_1080P60_MP3 = bytes(
  'R0AREABC8CUAAcEAAP8B/wAB/IAUSBIBBkZGbXBlZwlTZXJ2aWNlMDF3fEPK////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////////////////////////////////////////////////9HQAAQAACwDQABwQAAAAHwACqxBLL/////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '/0dQABAAArAXAAHBAADhAPAAG+EA8AAD4QHwAE5ZPR7/////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////R0EAMAdQAAB7DH4AAAAB4AAAgMAKMQAH79ERAAfYYQAAAAEJ' +
  '8AAAAAFnZAAqrNlAeAIn5cBEAAADAAQAAAMB4DxgxlgAAAABaOvjyyLAAAABBgX//6vcRem95tlIt5Ys2CDZI+7veDI2NCAtIGNv' +
  'cmUgMTY1IHIzMjIyIGIzNTYwNWEgLSBILjI2NC9NUEVHLTQgQVZDIGNvZGVjIC0gQ29weWxlZnQgMjAwMy0yMDI1IC0gaHR0cDov' +
  'L3dHAQARd3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFs' +
  'eXNlPTB4MzoweDExMyBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2' +
  'IGNocm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MSBjcW09MCBkZUcBABJhZHpvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9t' +
  'YV9xcF9vZmZzZXQ9LTIgdGhyZWFkcz0yNCBsb29rYWhlYWRfdGhyZWFkcz00IHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0' +
  'ZT0xIGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTMgYl9weXJhbWlkPTIg' +
  'Yl9h',
)

/** TS: HEVC Main, 1920x800, with AAC. */
export const TS_HEVC_MAIN_1920X800 = bytes(
  'R0AREABC8CUAAcEAAP8B/wAB/IAUSBIBBkZGbXBlZwlTZXJ2aWNlMDF3fEPK////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////////////////////////////////////////////////9HQAAQAACwDQABwQAAAAHwACqxBLL/////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '/0dQABAAArAdAAHBAADhAPAAJOEA8AYFBEhFVkMP4QHwAGw3z4r/////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////R0EAMAdQAAB7DH4AAAAB4AAAgMAKMQAJEvkRAAfYYQAAAAFG' +
  'AVAAAAABQAEMAf//AWAAAAMAkAAAAwAAAwB4lZgJAAAAAUIBAQFgAAADAJAAAAMAAAMAeKADwIAyFllZpJMrwFoCAAADAAIAAAMA' +
  'MBAAAAABRAHBcrRiQAAAASgBrx0aLYwhVDaIiriLEcNY2dYYaLbg9wI1f/92OfscAH9Eytru/xesO34/YOw8TgKrFtM+AUGpbNRE' +
  'aeZHAQAReuRdVDwQo3y/fhwKkPEbhaXpOXja/9v9DveSvsgoVWP//rvu5NY6Onk1pKgHIB4/tYeKhla4M7MfseXh/KH/z/7KcB1Y' +
  'RemmZnENfdaQO63FI/VkyKaMF4Xwhau644lOq/Tww5/8YpVyjlK+lo+YDACq0Z4UcsgSDJAa+pdt7WUvqikVG6hBaHUQPU1m2TCt' +
  'HYGhaAVPFe2wbgBWMtPI0eHw4H4IJ2m9e4s4gkE7ajRF1Gj2Iysk/UcBABIkct9nsZuBmQwJhhiESSidRTE0HqICn74SXe8gQJVd' +
  'xN8KPcJeKfm0FHZimIkKci9pcFdKZbMAv+xRhm/pYpJA7oKd6KGfKKcsWkkA9oIarNpPv8vFzgtAwNNK0t4KeEFoR9eixF5fFE+P' +
  'wABPs4X6mT99hNDoZoxuZyRLxxHMEO/HKrcXbFmd1ipc6RS/YbmRXSQwOf/60TI2wlnuBIHmBTBhD/D6x/o/vCAv9yAFxkIwAAAD' +
  'AC3e',
)

/** The head of a whole MP4 prepared for streaming: H.264 High 1280x536 at 24 fps with AAC, 2 s long; its `ftyp` and `moov`, and nothing of its `mdat`. */
export const WHOLE_MP4_HEAD = bytes(
  'AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAt5bW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAFYiAACsRAAAQAAAQAA' +
  'AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAA' +
  'BWN0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAACsRAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA' +
  'AAAAAAAAAAAAAABAAAAABQAAAAIYAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAArEQAAAEAAABAAAAAATbbWRpYQAAACBtZGhk' +
  'AAAAAAAAAAAAAAAAAAAwAAAAYABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAAEhm1p' +
  'bmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAABEZzdGJsAAAAwnN0c2QA' +
  'AAAAAAAAAQAAALJhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABQACGABIAAAASAAAAAAAAAABFExhdmM2My4xLjEwMiBsaWJ4' +
  'MjY0AAAAAAAAAAAAAAAAGP//AAAAOGF2Y0MBZAAf/+EAG2dkAB+s2UBQBF+XARAAAAMAEAAAAwMA8YMZYAEABmjr48siwP34+AAA' +
  'AAAQcGFzcAAAAAEAAAABAAAAFGJ0cnQAAAAAAAGlkAAAAAAAAAAYc3R0cwAAAAAAAAABAAAAMAAAAgAAAAAUc3RzcwAAAAAAAAAB' +
  'AAAAAQAAAYhjdHRzAAAAAAAAAC8AAAABAAAEAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAE' +
  'AAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAA' +
  'AAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEA' +
  'AAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQA' +
  'AAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAA' +
  'AQAAAgAAAAABAAAIAAAAAAIAAAIAAAAAKHN0c2MAAAAAAAAAAgAAAAEAAAACAAAAAQAAAAIAAAABAAAAAQAAANRzdHN6AAAAAAAA' +
  'AAAAAAAwAAActAAAA+YAAADNAAAA3QAAAL0AAAQTAAABEQAAANUAAADeAAAD/QAAAQMAAADKAAAAuQAAA5AAAADhAAAAvgAAAOAA' +
  'AAPdAAABHwAAAMEAAADoAAAE1wAAARwAAADYAAAA1AAAA8sAAADoAAAAygAAAM4AAAQEAAAA+gAAAMkAAADhAAAEFQAAARwAAADQ' +
  'AAAA1QAAA4gAAAD5AAAA5QAAAQYAAAOaAAABDgAAAL4AAADVAAACigAAAL8AAAD9AAAAzHN0Y28AAAAAAAAALwAAC6kAAC1DAAAv' +
  'qwAAMhsAADRFAAA5/wAAO+MAAD5bAABA4QAARm0AAEj6AABKrQAATNYAAFIfAABUfgAAVuIAAFifAABeEQAAYK4AAGMhAABlagAA' +
  'avkAAG24AABv+AAAcpQAAHf6AAB5qgAAe/QAAH5HAACD4AAAhmwAAIfwAACKhQAAkDIAAJLQAACVBgAAloUAAJviAACecQAAoOwA' +
  'AKKjAACn8QAAqm4AAKzBAACvPgAAsoEAALTkAAAFQXRyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAIAAAAAAAKxEAAAAAAAAAAA' +
  'AAAAAQEAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAA' +
  'AQACsRAAAAQAAAEAAAAABLltZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAAKxEAAFciFXEAAAAAAAtaGRscgAAAAAAAAAAc291bgAA' +
  'AAAAAAAAAAAAAFNvdW5kSGFuZGxlcgAAAARkbWluZgAAABBzbWhkAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAM' +
  'dXJsIAAAAAEAAAQoc3RibAAAAH5zdHNkAAAAAAAAAAEAAABubXA0YQAAAAAAAAABAAAAAAAAAAAAAQAQAAAAAKxEAAAAAAA2ZXNk' +
  'cwAAAAADgICAJQACAASAgIAXQBUAAAAAARA+AAEQPgWAgIAFEghW5QAGgICAAQIAAAAUYnRydAAAAAAAARA+AAEQPgAAACBzdHRz' +
  'AAAAAAAAAAIAAABXAAAEAAAAAAEAAACIAAABDHN0c2MAAAAAAAAAFQAAAAEAAAABAAAAAQAAAAIAAAACAAAAAQAAAAYAAAABAAAA' +
  'AQAAAAcAAAACAAAAAQAAAAsAAAABAAAAAQAAAAwAAAACAAAAAQAAABAAAAABAAAAAQAAABEAAAACAAAAAQAAABUAAAABAAAAAQAA' +
  'ABYAAAACAAAAAQAAABoAAAABAAAAAQAAABsAAAACAAAAAQAAAB8AAAABAAAAAQAAACAAAAACAAAAAQAAACQAAAABAAAAAQAAACUA' +
  'AAACAAAAAQAAACgAAAABAAAAAQAAACkAAAACAAAAAQAAAC0AAAABAAAAAQAAAC4AAAACAAAAAQAAAC8AAAAGAAAAAQAAAXRzdHN6' +
  'AAAAAAAAAAAAAABYAAABAAAAAQIAAACZAAAAuwAAANgAAACxAAAAvAAAAMcAAADgAAAA0wAAALoAAADpAAAA+gAAAK4AAADQAAAA' +
  'vwAAAKoAAADgAAAA6QAAALoAAAC2AAAA6QAAANAAAADUAAAAqgAAAMUAAADhAAAA3QAAAMEAAADUAAAArwAAAM8AAADmAAAAzAAA' +
  'ALAAAACxAAAAuAAAANcAAADMAAAArQAAALsAAADtAAAA2wAAANwAAAC/AAAAyAAAAKcAAADZAAAA0QAAALQAAADNAAAAyAAAANUA' +
  'AAC9AAAAuwAAAOUAAADPAAAAzAAAAMwAAACsAAAA1gAAALwAAACqAAAAqgAAAQIAAADTAAAA6gAAAKwAAADRAAAAxQAAALEAAAC4' +
  'AAAA/AAAAL0AAACyAAAAqwAAAOoAAADIAAAA4AAAALkAAADWAAAAzgAAALIAAAC0AAAAxQAAANsAAAD7AAAABQAAAMxzdGNvAAAA' +
  'AAAAAC8AACxDAAAuEAAAMIgAADLYAAA4WAAAOxAAADy4AAA/OQAARN4AAEdwAABJxAAAS2YAAFBmAABTAAAAVTwAAFfCAABcfAAA' +
  'XzAAAGFvAABkCQAAakEAAGwVAABukAAAcMwAAHZfAAB44gAAenQAAHzCAACCSwAAhNoAAIc1AACI0QAAjpoAAJFOAACToAAAldsA' +
  'AJoNAACc2wAAn1YAAKHyAACmPQAAqP8AAKssAACtlgAAscgAALNAAAC14QAAABpzZ3BkAQAAAHJvbGwAAAACAAAAAf//AAAAHHNi' +
  'Z3AAAAAAcm9sbAAAAAEAAABYAAAAAQAAAGF1ZHRhAAAAWW1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAA' +
  'AAAALGlsc3QAAAAkqXRvbwAAABxkYXRhAAAAAQAAAABMYXZmNjMuMS4xMDI=',
)
